### PR TITLE
fix include dependencies

### PR DESCRIPTION
**Pull request by antis81**
Minimizing the include dependencies in main app.

### CODE REVIEW

**Comment by antis81** [comment]
This is clearly not about performance (!) - the positive effect is barely noticeable in projects <100.000 LOC. It is about "learning to do the right thing" :smile:. Don't get me wrong: I'm not enforcing you to do it this way. Even more I'd love to figure out a **real** solution together with you to get rid of the warnings by solving them and to learn from this. All I can say is: I cannot predict the result, but this **is** the right way!

Btw.: I'm compiling with clang and regardless of this PR, it gives me ~2500 warnings. My guess is, this is about the same with GCC and also with VSC. These W's have to be resolved - and it is definitely possible without completely freaking out :smile:.

Please also have a look at the second commit, fixing the include paths.

Thus, the `QtIncludes` file is the next thing to get rid of :smile:.

**Comment by VioletGiraffe** [comment]
I'm all for doing things right. Let's discuss: pros and cons of your approach versus mine. 

 Pros of my approach:
* It solves the warnings problem and does not clutter .cpp files at the same time.
* It doesn't require any extra work as you create new files, while with your approach you do have to add the `pragma` wrapper in each new file.

Cons:
* It looks weird?.. I really don't see any downside.

Pros of your approach:
* It's the traditional way of managing includes - every .cpp includes _only_ the headers it needs. Dependency control.

Cons:
* All the pros of my solution  are negated.

I'm not saying my solution is the best, or the only, or should stay. As I said, let's discuss. Your turn :)

P. S. Is that 2500 warnings on Mac? There were _some_ the last time I've built it there, but certainly not thousands. Same for GCC 4.9 on Linux. I'll get to fixing them all, it's just that my primary development platform is Windows.

**Comment by antis81** [comment]
>P. S. Is that 2500 warnings on Mac?
First stop to look at is the compiler, which produces the warnings - not the OS. I think you know well, that different compilers produce different warnings. Nowadays this is not really difficult to solve - once you got the basis right. We get the warnings on Clang/GCC, because of that nasty `#ifdef _WIN32` ... see it? :)

>I'm not saying my solution is the best, or the only, or should stay. As I said, let's discuss. Your turn :)

Hm ... no, I don't counter argument - it's simply not worth it! But you might want to rethink the fact, that hiding a problem does not solve it - in any way. This is exactly what the `-w0` does here! I really hope you see this by yourself. Then question your arguments again - discussion over! :)

**Comment by VioletGiraffe** [comment]
>hiding a problem does not solve it
You're not saying I should edit the Qt headers, are you? Because that at best that's a bad idea, at worst that would require me to re-compile Qt. So the *only* meaningful thing I can do with the warnings in 3rd-party libraries is to suppress them.

>First stop to look at is the compiler, which produces the warnings - not the OS. 
You said clang, and the only desktop platform where clang is the default compiler is Mac OS. Which is why I asked if that was on Mac. Because I have built the program on Mac this week, and while there were *some* warning, there weren't thousands of them. Either way, they will all be squashed shortly, I just don't understand how you could get 2500. And what was that about `#ifdef _WIN32`? `#ifdef` can't produce a warning, for all I know...

**Comment by antis81** [comment]
I don't have much time. So please be patient. In short:

No, you don't require a Qt recompile and don't even think about changing the sources. There's something wrong with the c++11 switches (the "override" warning). I'd try to centralize these to the main .pro file `CONFIG += c++11` and remove the subproject's settings.

>You said clang, and the only desktop platform where clang is the default compiler is Mac OS.

I'm can seemlessly switch between clang and gcc on my Linux setup. One of the reasons I wrote it is "highly customized" :).

>And what was that about #ifdef _WIN32? #ifdef can't produce a warning, for all I know...

What I mean is, that you don't want those `#ifdef's` in your code ... It duplicates code for the OS and is really error prone, as most likely you test for your "favorite" OS only - naturally.

**Comment by VioletGiraffe** [comment]
>There's something wrong with the c++11 switches (the "override" warning)

Maybe that is the only problem on Linux with clang. But take a look at the list of warnings on Windows (MSVC 2013): https://gist.github.com/VioletGiraffe/755cdb87fd3c4b95f5bb

>What I mean is, that you don't want those #ifdef's in your code 
Either way, I do need platform-specific code, so the question is how to implement it. I can think of 3 different methods:
1. `#ifdef` (conditional compilation)
2. isolating the method(s) of the class that need different behavior on different systems and implementing them in different .cpp files: `classname_win.cpp`, `classname_osx.cpp` etc. (conditional project generation).
3. Making those methods `virtual` and creating a base class (if applicable) and a specific class for each platform (polymorphism, late binding). And you probably still need `#ifdef` to instantiate the right class :P

I think it boils down to personal preference, but method 1 often allows to achieve as little code duplication as possible - less than with methods 2. and 3. As a rule of thumb, I prefer `#ifdef` when the platform-specific code is very short, *or* when it's not very long and `#ifdef` does allow for less code duplication. Otherwise, I prefer method 2.

**Comment by VioletGiraffe** [comment]
I've accepted your commits... and went much further! There are no `QtInclude` headers now, every header and every .cpp only includes the headers it actually needs :)

**Comment by antis81** [comment]
Yes cool :sunglasses:. The `DISABLE / ENABLE` macros are ok - though actually they should disappear somewhere in the future.

GCC compiles fine without warnings; those `override` warnings on Clang were introduced recently and should actually be fixed in the upcoming Qt5.5 release. A fix is on it's way and there's basically nothing we can do about it. Nothing to worry about really.

So in general we're on a good way now :+1:.

**Comment by antis81** [comment]
Almost forgot: There's one missing include in `casynctask.h`, which leads to a compiler error:

```c++
#ifdef QT_VERSION
#include <QDebug>
#endif
```

**Comment by VioletGiraffe** [comment]
There are indeed no warnings with GCC; the clang ones might be fixed, but there are LOTS of warnings on Windows with MSVC. They're all, of course, are caused by pretty silly things: mostly types mismatch and compile-time-constant conditions.
Perhaps, I should report them to the Qt bug tracker?..

**Comment by antis81** [comment]
>Perhaps, I should report them to the Qt bug tracker?

There's a good chance those are already posted, but it is definitely worth the time.

**Comment by VioletGiraffe** [comment]
>There's a good chance those are already posted

Indeed. But it's not like those warnings appeared yesterday. They could be as old as Qt 5.0 for all I know.
And I've fixed the missing include and will commit it shortly.

**Comment by antis81** [comment]
There's an official [release plan](https://wiki.qt.io/Qt-5.5-release) available ... didn't know that. For the above mentioned, you might want to have a look [here](https://bugreports.qt.io/browse/QTBUG-46863). If this 

I've not seen Windows for quite some time now. Support for Windows >=8 came pretty late last year and was not there at all in Qt 5.0.

**Comment by VioletGiraffe** [comment]
>Support for Windows >=8 came pretty late last year and was not there at all in Qt 5.0.

Not sure at all what you mean by that. My Qt apps were running just fine on Windows 8 right when the beta came out, let alone the release. Even more so, one of my work projects still uses Qt 4.8 and runs no problem on Windows XP through 10.

**Pull request merged**
