### PR TITLE
fix linux build

### PR DESCRIPTION
**Pull request by antis81**
Heya, I had a look into the code and made it compile on Linux :smile:. Instead of merging the PR, you can either cherry-pick this one or simply correct the two lines by yourself.

Feels somewhat weird seeing a midnight commander clone again after a long time - I like the idea doing it with Qt :+1:.

### CODE REVIEW

**Comment by antis81** [comment]
Oh, didn't see you did the same. Closing!

**Comment by VioletGiraffe** [comment]
Oh well. I didn't try Linux for a good while, but I did fix build for Mac OS X today :)

I have actually not used Midnight Commander, so any resemblance is incidental. In fact, I don't even think I ever see it. I was inspired by Total Commander (the best file manager for Windows).
Qt is simply the best library for cross-platform GUI for C++ applications, so it's pretty much the only choice. And I like it, too. I do have a desire to implement completely native, Qt-less thin UI for each system. But my UI has grown too large (needs refactoring), and there's no immediate call for it anyway. Qt may not look 100% native, but it's great for prototyping which is pretty much what I'm doing so far.

**Comment by antis81** [comment]
Well ... here it is - in it's full beauty:

file-commander-lubuntu

On the left side you see the recent version of PCManFM-Qt - which is my default FM. Btw. I'm a proud owner of a highly customized Lubuntu/LXQt running on a Macbook :+1: :heart:.

Just for some historical background it's a good idea to google Midnight Commander / Norton Commander. Total Commander was greatly inspired by those and I also used it for years until I left Windows behind ...

**Comment by VioletGiraffe** [comment]
Linux on a Macbook? Nice! :) Cover the Apple logo on the lid with a penguin sticker :)
The UI looks OK to me, for the most part. I need to find a way to filter out weird mount points like that `gvfs` one.

I have used Norton Commander extensively myself, back when parents had a 286 PC running DOS. But now I like UIs that are pretty, intuitive and graphical.

**Comment by antis81** [comment]
>... I need to find a way to filter out weird mount points like that gvfs one.

This was incidentally, but there's some things to do to get this right: First stop for this one is `QDir::cleanPath` and `QDir::drives`. Other than that, you can check `QFileInfo`. Also have a look at this [StackOverflow](http://stackoverflow.com/questions/18600377/detecting-mounted-drives-on-linux-and-mac-os-x) article.

**Comment by VioletGiraffe** [comment]
My own SO question, he-he. I'd hoped `QStorageInfo` will relieve me of this suffering, but apparently not, not entirely.

**Comment by antis81** [comment]
Ooops bulls eye :dart: :smile:. Although this is a bit of cheating ... you might want to have a look inside [PCManFM-Qt](https://github.com/lxqt/pcmanfm-qt). This is showing the devices (plus unmounted and network) within the "places" view.

**Comment by VioletGiraffe** [comment]
I might want to look at it, thanks!

**Comment by antis81** [comment]
Oh forgot ... Bear in mind to use `QString::fromUtf8` rather than `fromLocal8bit`.

**Comment by VioletGiraffe** [comment]
I don't seem to be using `fromLocal8bit` anywhere at all.

**Pull request closed without merging**
